#!/usr/bin/env python
import sys, webbrowser
import stallion.main as stall
from multiprocessing import Process


def s(): #arbitary function to run as a process
    stall.run_main()
def w(): #arbitary function to run as a process
		webbrowser.open('http://localhost:5000')

if __name__ == '__main__':
		sp = Process(target=s)
		wp = Process(target=w)

		if len(sys.argv) > 1:
			sp.start()
		else:
			sp.start()
			wp.start()
		


